#!/usr/bin/env python3
"""
包括的なカテゴリ定義システム
将来のデータ拡張に備えて、0人でも全カテゴリを定義
"""

COMPREHENSIVE_CATEGORIES = {
    # ============ メインカテゴリ ============
    'main_categories': {
        '科学・学術': {
            '物理学者': ['physicist', 'physics', '物理学'],
            '化学者': ['chemist', 'chemistry', '化学'],
            '生物学者': ['biologist', 'biology', '生物学'],
            '数学者': ['mathematician', 'mathematics', '数学'],
            '天文学者': ['astronomer', 'astronomy', '天文学'],
            '地質学者': ['geologist', 'geology', '地質学'],
            '医学者': ['physician', 'doctor', 'medical', '医学'],
            '薬学者': ['pharmacist', 'pharmacy', '薬学'],
            '工学者': ['engineer', 'engineering', '工学'],
            'コンピュータ科学者': ['computer scientist', 'programmer', 'プログラマー'],
            'AI研究者': ['ai researcher', 'artificial intelligence', 'AI'],
            '心理学者': ['psychologist', 'psychology', '心理学'],
            '社会学者': ['sociologist', 'sociology', '社会学'],
            '人類学者': ['anthropologist', 'anthropology', '人類学'],
            '考古学者': ['archaeologist', 'archaeology', '考古学'],
            '言語学者': ['linguist', 'linguistics', '言語学'],
            '経済学者': ['economist', 'economics', '経済学'],
            '歴史学者': ['historian', 'history', '歴史学'],
            '地理学者': ['geographer', 'geography', '地理学'],
            '気象学者': ['meteorologist', 'meteorology', '気象学'],
            '海洋学者': ['oceanographer', 'oceanography', '海洋学'],
            '宇宙飛行士': ['astronaut', 'cosmonaut', '宇宙飛行士'],
            'ノーベル賞受賞科学者': ['nobel laureate scientist'],
        },
        
        '芸術': {
            '画家': ['painter', 'painting', '画家'],
            '彫刻家': ['sculptor', 'sculpture', '彫刻家'],
            '版画家': ['printmaker', 'engraver', '版画家'],
            '書道家': ['calligrapher', 'calligraphy', '書道家'],
            '陶芸家': ['potter', 'ceramist', '陶芸家'],
            '写真家': ['photographer', 'photography', '写真家'],
            '建築家': ['architect', 'architecture', '建築家'],
            'デザイナー': ['designer', 'design', 'デザイナー'],
            'ファッションデザイナー': ['fashion designer', 'ファッション'],
            'グラフィックデザイナー': ['graphic designer', 'グラフィック'],
            'プロダクトデザイナー': ['product designer', 'プロダクト'],
            'インテリアデザイナー': ['interior designer', 'インテリア'],
            'イラストレーター': ['illustrator', 'illustration', 'イラスト'],
            '漫画家': ['manga artist', 'cartoonist', '漫画家'],
            'アニメーター': ['animator', 'animation', 'アニメ'],
            '現代美術家': ['contemporary artist', '現代美術'],
            'ストリートアーティスト': ['street artist', 'graffiti'],
            'インスタレーション作家': ['installation artist'],
            'パフォーマンスアーティスト': ['performance artist'],
            'デジタルアーティスト': ['digital artist', 'NFT'],
        },
        
        '音楽': {
            'クラシック作曲家': ['classical composer', 'baroque', 'romantic'],
            '現代音楽作曲家': ['contemporary composer', 'modern'],
            '映画音楽作曲家': ['film composer', 'soundtrack'],
            'ゲーム音楽作曲家': ['game composer', 'video game music'],
            '指揮者': ['conductor', 'maestro', '指揮者'],
            'ピアニスト': ['pianist', 'piano', 'ピアニスト'],
            'ヴァイオリニスト': ['violinist', 'violin', 'ヴァイオリン'],
            'チェリスト': ['cellist', 'cello', 'チェロ'],
            'ギタリスト': ['guitarist', 'guitar', 'ギター'],
            'ドラマー': ['drummer', 'drums', 'ドラム'],
            'ベーシスト': ['bassist', 'bass', 'ベース'],
            'オペラ歌手': ['opera singer', 'soprano', 'tenor'],
            'ポップス歌手': ['pop singer', 'pop artist'],
            'ロック歌手': ['rock singer', 'rock star'],
            'ジャズ音楽家': ['jazz musician', 'jazz'],
            'ブルース音楽家': ['blues musician', 'blues'],
            'カントリー歌手': ['country singer', 'country'],
            'ヒップホップアーティスト': ['hip hop artist', 'rapper'],
            'EDMアーティスト': ['EDM artist', 'DJ', 'electronic'],
            'フォーク歌手': ['folk singer', 'folk'],
            'レゲエアーティスト': ['reggae artist', 'reggae'],
            'K-POPアーティスト': ['k-pop', 'korean pop'],
            'J-POPアーティスト': ['j-pop', 'japanese pop'],
            'グラミー賞受賞者': ['grammy winner', 'grammy award'],
        },
        
        '文学・執筆': {
            '小説家': ['novelist', 'fiction writer', '小説家'],
            '詩人': ['poet', 'poetry', '詩人'],
            '劇作家': ['playwright', 'dramatist', '劇作家'],
            '脚本家': ['screenwriter', 'scriptwriter', '脚本家'],
            'エッセイスト': ['essayist', 'essay', 'エッセイ'],
            'ジャーナリスト': ['journalist', 'reporter', '記者'],
            'コラムニスト': ['columnist', 'column', 'コラム'],
            '批評家': ['critic', 'reviewer', '批評家'],
            '翻訳家': ['translator', 'translation', '翻訳家'],
            '編集者': ['editor', 'publisher', '編集者'],
            '児童文学作家': ['children author', 'young adult'],
            'SF作家': ['science fiction writer', 'sci-fi'],
            'ミステリー作家': ['mystery writer', 'detective'],
            'ファンタジー作家': ['fantasy writer', 'fantasy'],
            'ノンフィクション作家': ['non-fiction writer'],
            '伝記作家': ['biographer', 'biography'],
            'ブロガー': ['blogger', 'blog'],
            'コピーライター': ['copywriter', 'copy'],
            'ノーベル文学賞受賞者': ['nobel literature'],
            'ピューリッツァー賞受賞者': ['pulitzer prize'],
        },
        
        'エンターテインメント': {
            '映画俳優': ['film actor', 'movie star', '映画俳優'],
            '舞台俳優': ['stage actor', 'theater', '舞台俳優'],
            'テレビ俳優': ['tv actor', 'television', 'テレビ'],
            '声優': ['voice actor', 'voice actress', '声優'],
            'コメディアン': ['comedian', 'comic', 'コメディアン'],
            '映画監督': ['film director', 'filmmaker', '映画監督'],
            'プロデューサー': ['producer', 'production', 'プロデューサー'],
            '撮影監督': ['cinematographer', 'director of photography'],
            '編集技師': ['film editor', 'editing'],
            '音響技師': ['sound engineer', 'audio'],
            '特殊効果': ['special effects', 'VFX', 'CGI'],
            'スタントマン': ['stunt performer', 'stuntman'],
            'ダンサー': ['dancer', 'dance', 'ダンサー'],
            '振付師': ['choreographer', 'choreography'],
            'マジシャン': ['magician', 'illusionist', 'マジシャン'],
            'サーカス': ['circus performer', 'acrobat'],
            'YouTuber': ['youtuber', 'youtube creator'],
            'TikToker': ['tiktoker', 'tiktok creator'],
            'ストリーマー': ['streamer', 'twitch'],
            'インフルエンサー': ['influencer', 'social media'],
            'アカデミー賞受賞者': ['oscar winner', 'academy award'],
            'エミー賞受賞者': ['emmy winner', 'emmy award'],
            'トニー賞受賞者': ['tony award', 'broadway'],
            'カンヌ映画祭受賞者': ['cannes winner', 'palme'],
        },
        
        'スポーツ': {
            'サッカー選手': ['soccer player', 'footballer', 'サッカー'],
            '野球選手': ['baseball player', 'baseball', '野球'],
            'バスケットボール選手': ['basketball player', 'NBA'],
            'テニス選手': ['tennis player', 'tennis', 'テニス'],
            'ゴルフ選手': ['golfer', 'golf', 'ゴルフ'],
            'ラグビー選手': ['rugby player', 'rugby'],
            'アメフト選手': ['american football', 'NFL'],
            'クリケット選手': ['cricket player', 'cricket'],
            'ボクサー': ['boxer', 'boxing', 'ボクシング'],
            '格闘家': ['martial artist', 'MMA', 'UFC'],
            'レスラー': ['wrestler', 'wrestling', 'レスリング'],
            '柔道家': ['judoka', 'judo', '柔道'],
            '空手家': ['karateka', 'karate', '空手'],
            '体操選手': ['gymnast', 'gymnastics', '体操'],
            '陸上選手': ['track and field', 'athlete', '陸上'],
            '水泳選手': ['swimmer', 'swimming', '水泳'],
            'フィギュアスケート選手': ['figure skater', 'フィギュア'],
            'スキー選手': ['skier', 'skiing', 'スキー'],
            'スノーボード選手': ['snowboarder', 'snowboard'],
            '自転車選手': ['cyclist', 'cycling', '自転車'],
            'F1ドライバー': ['F1 driver', 'formula one'],
            'ラリードライバー': ['rally driver', 'WRC'],
            'バイクレーサー': ['motorcycle racer', 'MotoGP'],
            'eスポーツ選手': ['esports player', 'pro gamer'],
            'チェス選手': ['chess player', 'grandmaster'],
            '囲碁棋士': ['go player', '囲碁', '棋士'],
            '将棋棋士': ['shogi player', '将棋'],
            'オリンピック金メダリスト': ['olympic gold', 'olympian'],
            'パラリンピック選手': ['paralympian', 'paralympics'],
            'FIFA選手': ['FIFA player', 'world cup'],
            'スポーツ殿堂入り': ['hall of fame', 'HOF'],
        },
        
        '政治・指導者': {
            '大統領': ['president', '大統領'],
            '首相': ['prime minister', 'premier', '首相'],
            '国王': ['king', 'monarch', '国王'],
            '女王': ['queen', 'empress', '女王'],
            '皇帝': ['emperor', '皇帝'],
            '独裁者': ['dictator', 'autocrat', '独裁者'],
            '革命家': ['revolutionary', 'revolution', '革命家'],
            '独立運動家': ['independence leader', '独立'],
            '議員': ['parliament', 'congress', 'senator'],
            '知事': ['governor', 'prefect', '知事'],
            '市長': ['mayor', 'lord mayor', '市長'],
            '外交官': ['diplomat', 'ambassador', '外交官'],
            '国連事務総長': ['UN secretary general'],
            'EU指導者': ['EU leader', 'european'],
            '政党党首': ['party leader', 'chairman'],
            '内閣閣僚': ['cabinet minister', 'secretary'],
            '最高裁判事': ['supreme court justice'],
            '中央銀行総裁': ['central bank governor'],
            'ノーベル平和賞受賞者': ['nobel peace prize'],
        },
        
        '軍事': {
            '将軍': ['general', 'field marshal', '将軍'],
            '提督': ['admiral', 'fleet admiral', '提督'],
            '元帥': ['marshal', 'generalissimo', '元帥'],
            '大佐': ['colonel', 'captain', '大佐'],
            'パイロット': ['pilot', 'aviator', 'パイロット'],
            '特殊部隊': ['special forces', 'commando'],
            '傭兵': ['mercenary', 'soldier of fortune'],
            '武将': ['samurai', 'shogun', '武将'],
            '騎士': ['knight', 'crusader', '騎士'],
            '海賊': ['pirate', 'privateer', '海賊'],
            'スパイ': ['spy', 'intelligence', 'スパイ'],
            '戦争英雄': ['war hero', 'veteran'],
            '軍事戦略家': ['military strategist', 'tactician'],
            '兵器開発者': ['weapons developer', 'arms'],
        },
        
        'ビジネス・産業': {
            '起業家': ['entrepreneur', 'founder', '起業家'],
            'CEO': ['CEO', 'chief executive', 'CEO'],
            'CFO': ['CFO', 'chief financial'],
            'CTO': ['CTO', 'chief technology'],
            '投資家': ['investor', 'venture capitalist'],
            '銀行家': ['banker', 'banking', '銀行家'],
            '実業家': ['industrialist', 'tycoon', '実業家'],
            '不動産王': ['real estate', 'property'],
            '石油王': ['oil magnate', 'petroleum'],
            '鉄道王': ['railroad baron', 'railway'],
            '鉄鋼王': ['steel magnate', 'iron'],
            'IT起業家': ['tech entrepreneur', 'silicon valley'],
            'スタートアップ創業者': ['startup founder', 'unicorn'],
            '社会起業家': ['social entrepreneur'],
            'フィランソロピスト': ['philanthropist', 'charity'],
            '経営コンサルタント': ['management consultant'],
            'マーケター': ['marketer', 'marketing'],
            'フォーブス長者番付': ['forbes billionaire'],
            'フォーチュン500 CEO': ['fortune 500'],
        },
        
        '宗教・哲学': {
            '哲学者': ['philosopher', 'philosophy', '哲学者'],
            '神学者': ['theologian', 'theology', '神学者'],
            'ローマ教皇': ['pope', 'pontiff', '教皇'],
            '枢機卿': ['cardinal', 'archbishop'],
            '司教': ['bishop', 'diocese'],
            '牧師': ['pastor', 'minister', '牧師'],
            '神父': ['priest', 'father', '神父'],
            '修道士': ['monk', 'friar', '修道士'],
            '修道女': ['nun', 'sister', '修道女'],
            'ラビ': ['rabbi', 'jewish', 'ラビ'],
            'イマーム': ['imam', 'muslim', 'イマーム'],
            '僧侶': ['buddhist monk', '僧侶', '坊さん'],
            '神主': ['shinto priest', '神主', '宮司'],
            'ダライ・ラマ': ['dalai lama', 'tibet'],
            'グル': ['guru', 'spiritual leader'],
            '宗教改革者': ['religious reformer'],
            '聖人': ['saint', 'holy', '聖人'],
            '預言者': ['prophet', 'messenger'],
            '神秘主義者': ['mystic', 'mysticism'],
        },
        
        '活動家・社会運動': {
            '人権活動家': ['human rights', 'civil rights'],
            '女性運動家': ['feminist', 'women rights'],
            '環境活動家': ['environmental', 'climate activist'],
            '平和活動家': ['peace activist', 'pacifist'],
            '労働運動家': ['labor activist', 'union'],
            'LGBTQ活動家': ['LGBTQ activist', 'pride'],
            '動物愛護活動家': ['animal rights', 'vegan'],
            '反戦活動家': ['anti-war', 'protest'],
            '市民運動家': ['civil activist', 'grassroots'],
            '教育改革者': ['education reformer'],
            '医療改革者': ['healthcare reformer'],
            '刑事司法改革者': ['criminal justice reform'],
            '反人種差別活動家': ['anti-racism', 'BLM'],
            '反核活動家': ['anti-nuclear', 'disarmament'],
            'NGO創設者': ['NGO founder', 'non-profit'],
        },
        
        '法律・司法': {
            '弁護士': ['lawyer', 'attorney', '弁護士'],
            '検察官': ['prosecutor', 'district attorney'],
            '裁判官': ['judge', 'justice', '裁判官'],
            '最高裁判事': ['supreme court', 'high court'],
            '法学者': ['legal scholar', 'jurist'],
            '国際法専門家': ['international law'],
            '憲法学者': ['constitutional scholar'],
            '刑法専門家': ['criminal law'],
            '民法専門家': ['civil law'],
            '商法専門家': ['commercial law'],
            '人権弁護士': ['human rights lawyer'],
            '企業弁護士': ['corporate lawyer'],
            '特許弁護士': ['patent attorney'],
            '国際司法裁判所判事': ['ICJ judge'],
        },
        
        '教育': {
            '教育者': ['educator', 'teacher', '教師'],
            '大学教授': ['professor', 'academic', '教授'],
            '学長': ['university president', 'chancellor'],
            '教育改革者': ['education reformer'],
            '幼児教育者': ['early childhood educator'],
            '特別支援教育者': ['special education'],
            '職業訓練指導者': ['vocational trainer'],
            'オンライン教育者': ['online educator', 'MOOC'],
            '教育理論家': ['education theorist'],
            '学習科学研究者': ['learning scientist'],
        },
        
        '探検・冒険': {
            '探検家': ['explorer', 'expedition', '探検家'],
            '航海者': ['navigator', 'sailor', '航海者'],
            '登山家': ['mountaineer', 'climber', '登山家'],
            '極地探検家': ['polar explorer', 'arctic'],
            '深海探検家': ['deep sea explorer', 'ocean'],
            '宇宙探検家': ['space explorer', 'astronaut'],
            '洞窟探検家': ['cave explorer', 'spelunker'],
            '冒険家': ['adventurer', 'expedition'],
            '旅行家': ['traveler', 'voyager'],
            '自然写真家': ['nature photographer', 'wildlife'],
        },
        
        'メディア・放送': {
            'アナウンサー': ['announcer', 'anchor', 'アナウンサー'],
            'ニュースキャスター': ['news anchor', 'newscaster'],
            'ラジオDJ': ['radio DJ', 'radio host'],
            'テレビ司会者': ['TV host', 'presenter'],
            'ポッドキャスター': ['podcaster', 'podcast host'],
            '気象予報士': ['weather forecaster', 'meteorologist'],
            'スポーツキャスター': ['sports commentator'],
            'ドキュメンタリー制作者': ['documentary filmmaker'],
            'ビデオグラファー': ['videographer', 'video'],
        },
        
        '料理・食文化': {
            'シェフ': ['chef', 'cook', 'シェフ'],
            'パティシエ': ['pastry chef', 'patissier'],
            'バリスタ': ['barista', 'coffee'],
            'ソムリエ': ['sommelier', 'wine expert'],
            '料理研究家': ['culinary researcher', '料理研究家'],
            'フードライター': ['food writer', 'critic'],
            'レストラン経営者': ['restaurateur'],
            'ミシュランシェフ': ['michelin star chef'],
            '郷土料理専門家': ['regional cuisine expert'],
            '栄養士': ['nutritionist', 'dietitian'],
        },
        
        'ファッション・美容': {
            'ファッションデザイナー': ['fashion designer', 'couture'],
            'モデル': ['model', 'supermodel', 'モデル'],
            'スタイリスト': ['stylist', 'fashion stylist'],
            'メイクアップアーティスト': ['makeup artist', 'MUA'],
            'ヘアスタイリスト': ['hairstylist', 'hairdresser'],
            'ファッション写真家': ['fashion photographer'],
            'ファッションエディター': ['fashion editor', 'vogue'],
            'ジュエリーデザイナー': ['jewelry designer'],
            '香水調香師': ['perfumer', 'fragrance'],
            'ファッションアイコン': ['fashion icon', 'style icon'],
        },
    },
    
    # ============ 時代カテゴリ ============
    'era_categories': {
        '先史時代': 'prehistoric',
        '古代（紀元前3000年以前）': 'ancient_early',
        '古代（紀元前3000-1000年）': 'ancient_mid',
        '古代（紀元前1000-1年）': 'ancient_late',
        '古代（紀元後1-500年）': 'ancient_ad',
        '中世前期（500-1000年）': 'medieval_early',
        '中世盛期（1000-1250年）': 'medieval_high',
        '中世後期（1250-1500年）': 'medieval_late',
        'ルネサンス（1400-1600年）': 'renaissance',
        '近世（1500-1700年）': 'early_modern',
        '啓蒙時代（1700-1800年）': 'enlightenment',
        '産業革命期（1760-1840年）': 'industrial_revolution',
        '19世紀前半（1800-1850年）': '19th_early',
        '19世紀後半（1850-1900年）': '19th_late',
        'ベル・エポック（1871-1914年）': 'belle_epoque',
        '第一次世界大戦期（1914-1918年）': 'wwi',
        '戦間期（1918-1939年）': 'interwar',
        '第二次世界大戦期（1939-1945年）': 'wwii',
        '冷戦前期（1945-1970年）': 'cold_war_early',
        '冷戦後期（1970-1991年）': 'cold_war_late',
        'ポスト冷戦（1991-2001年）': 'post_cold_war',
        '21世紀初頭（2001-2010年）': '21st_early',
        '21世紀中期（2010-2020年）': '21st_mid',
        '現代（2020年-）': 'contemporary',
    },
    
    # ============ 地域カテゴリ ============
    'region_categories': {
        # 北アメリカ
        'アメリカ合衆国': 'USA',
        'カナダ': 'Canada',
        'メキシコ': 'Mexico',
        '中央アメリカ': 'Central_America',
        'カリブ海地域': 'Caribbean',
        
        # 南アメリカ
        'ブラジル': 'Brazil',
        'アルゼンチン': 'Argentina',
        'チリ': 'Chile',
        'ペルー': 'Peru',
        'コロンビア': 'Colombia',
        'ベネズエラ': 'Venezuela',
        '南米その他': 'South_America_Other',
        
        # ヨーロッパ
        'イギリス': 'UK',
        'フランス': 'France',
        'ドイツ': 'Germany',
        'イタリア': 'Italy',
        'スペイン': 'Spain',
        'ポルトガル': 'Portugal',
        'オランダ': 'Netherlands',
        'ベルギー': 'Belgium',
        'スイス': 'Switzerland',
        'オーストリア': 'Austria',
        'ポーランド': 'Poland',
        'ロシア': 'Russia',
        'ウクライナ': 'Ukraine',
        '北欧': 'Nordic',
        'バルカン半島': 'Balkans',
        'バルト三国': 'Baltic',
        '東欧': 'Eastern_Europe',
        
        # アジア
        '日本': 'Japan',
        '中国': 'China',
        '韓国': 'South_Korea',
        '北朝鮮': 'North_Korea',
        '台湾': 'Taiwan',
        'インド': 'India',
        'パキスタン': 'Pakistan',
        'バングラデシュ': 'Bangladesh',
        'タイ': 'Thailand',
        'ベトナム': 'Vietnam',
        'インドネシア': 'Indonesia',
        'フィリピン': 'Philippines',
        'マレーシア': 'Malaysia',
        'シンガポール': 'Singapore',
        '東南アジアその他': 'Southeast_Asia_Other',
        '中央アジア': 'Central_Asia',
        
        # 中東
        'イスラエル': 'Israel',
        'パレスチナ': 'Palestine',
        'エジプト': 'Egypt',
        'サウジアラビア': 'Saudi_Arabia',
        'アラブ首長国連邦': 'UAE',
        'イラン': 'Iran',
        'イラク': 'Iraq',
        'シリア': 'Syria',
        'レバノン': 'Lebanon',
        'ヨルダン': 'Jordan',
        'トルコ': 'Turkey',
        '中東その他': 'Middle_East_Other',
        
        # アフリカ
        '南アフリカ': 'South_Africa',
        'ナイジェリア': 'Nigeria',
        'エチオピア': 'Ethiopia',
        'ケニア': 'Kenya',
        'ガーナ': 'Ghana',
        'モロッコ': 'Morocco',
        'アルジェリア': 'Algeria',
        'チュニジア': 'Tunisia',
        'リビア': 'Libya',
        '西アフリカ': 'West_Africa',
        '東アフリカ': 'East_Africa',
        '中央アフリカ': 'Central_Africa',
        '北アフリカ': 'North_Africa',
        
        # オセアニア
        'オーストラリア': 'Australia',
        'ニュージーランド': 'New_Zealand',
        '太平洋諸島': 'Pacific_Islands',
        
        # 古代文明
        '古代エジプト': 'Ancient_Egypt',
        '古代ギリシャ': 'Ancient_Greece',
        '古代ローマ': 'Ancient_Rome',
        '古代中国': 'Ancient_China',
        '古代インド': 'Ancient_India',
        'メソポタミア': 'Mesopotamia',
        'ペルシャ帝国': 'Persian_Empire',
        'ビザンティン帝国': 'Byzantine_Empire',
        'オスマン帝国': 'Ottoman_Empire',
        'モンゴル帝国': 'Mongol_Empire',
    },
    
    # ============ 特別タグ ============
    'special_tags': {
        # 受賞歴
        'ノーベル賞受賞者': 'Nobel_Prize',
        'ノーベル物理学賞': 'Nobel_Physics',
        'ノーベル化学賞': 'Nobel_Chemistry',
        'ノーベル生理学・医学賞': 'Nobel_Medicine',
        'ノーベル文学賞': 'Nobel_Literature',
        'ノーベル平和賞': 'Nobel_Peace',
        'ノーベル経済学賞': 'Nobel_Economics',
        
        'アカデミー賞受賞者': 'Academy_Award',
        'アカデミー作品賞': 'Oscar_Best_Picture',
        'アカデミー監督賞': 'Oscar_Best_Director',
        'アカデミー主演男優賞': 'Oscar_Best_Actor',
        'アカデミー主演女優賞': 'Oscar_Best_Actress',
        
        'グラミー賞受賞者': 'Grammy_Award',
        'エミー賞受賞者': 'Emmy_Award',
        'トニー賞受賞者': 'Tony_Award',
        'ゴールデングローブ賞': 'Golden_Globe',
        'カンヌ映画祭パルムドール': 'Palme_dOr',
        'ヴェネツィア映画祭金獅子賞': 'Golden_Lion',
        'ベルリン映画祭金熊賞': 'Golden_Bear',
        
        'フィールズ賞': 'Fields_Medal',
        'チューリング賞': 'Turing_Award',
        'プリツカー賞': 'Pritzker_Prize',
        'ピューリッツァー賞': 'Pulitzer_Prize',
        'ブッカー賞': 'Booker_Prize',
        '芥川賞': 'Akutagawa_Prize',
        '直木賞': 'Naoki_Prize',
        
        # スポーツ関連
        'オリンピック金メダリスト': 'Olympic_Gold',
        'オリンピック複数メダリスト': 'Olympic_Multiple',
        'パラリンピックメダリスト': 'Paralympic_Medal',
        'FIFAワールドカップ優勝': 'World_Cup_Winner',
        'UEFA欧州選手権優勝': 'Euro_Winner',
        'バロンドール受賞者': 'Ballon_dOr',
        'FIFA年間最優秀選手': 'FIFA_Best',
        'MLB殿堂入り': 'MLB_Hall_of_Fame',
        'NBA殿堂入り': 'NBA_Hall_of_Fame',
        'NFL殿堂入り': 'NFL_Hall_of_Fame',
        
        # 年齢・寿命関連
        '長寿（100歳以上）': 'Centenarian',
        '超長寿（110歳以上）': 'Supercentenarian',
        '若逝（30歳以下）': 'Died_Young_30',
        '若逝（40歳以下）': 'Died_Young_40',
        '若逝（50歳以下）': 'Died_Young_50',
        '夭折（20歳以下）': 'Died_Very_Young',
        '暗殺・処刑': 'Assassinated',
        '戦死': 'Killed_in_War',
        '事故死': 'Accidental_Death',
        '自殺': 'Suicide',
        
        # 国籍・民族
        '日本人': 'Japanese',
        '在日外国人': 'Foreign_in_Japan',
        '日系人': 'Japanese_Descent',
        '華僑': 'Overseas_Chinese',
        'ユダヤ系': 'Jewish',
        'アフリカ系アメリカ人': 'African_American',
        'ヒスパニック系': 'Hispanic',
        'ネイティブアメリカン': 'Native_American',
        'アボリジニ': 'Aboriginal',
        
        # 性別・ジェンダー
        '女性先駆者': 'Female_Pioneer',
        '初の女性○○': 'First_Female',
        'LGBTQ+': 'LGBTQ',
        'トランスジェンダー': 'Transgender',
        
        # その他の特徴
        '億万長者': 'Billionaire',
        'フォーブス400': 'Forbes_400',
        'タイム誌今年の人': 'TIME_Person_of_Year',
        '国民栄誉賞': 'Peoples_Honor_Award',
        '文化勲章': 'Order_of_Culture',
        '勲一等': 'Grand_Cordon',
        'ナイト爵位': 'Knighthood',
        '名誉市民': 'Honorary_Citizen',
        '天才児': 'Child_Prodigy',
        'IQ180以上': 'Genius_IQ',
        '複数分野で活躍': 'Renaissance_Person',
        '社会変革者': 'Social_Reformer',
        '発明の父/母': 'Father_of_Invention',
        '○○の開拓者': 'Pioneer',
        '伝説的人物': 'Legendary_Figure',
        '歴史を変えた人物': 'Changed_History',
        '世界遺産関連': 'World_Heritage',
        'ギネス記録保持者': 'Guinness_Record',
    }
}

def export_category_structure():
    """カテゴリ構造をJSONファイルとして出力"""
    import json
    from datetime import datetime
    
    # 統計情報を計算
    stats = {
        'main_categories_count': sum(len(subcats) for subcats in COMPREHENSIVE_CATEGORIES['main_categories'].values()),
        'era_categories_count': len(COMPREHENSIVE_CATEGORIES['era_categories']),
        'region_categories_count': len(COMPREHENSIVE_CATEGORIES['region_categories']),
        'special_tags_count': len(COMPREHENSIVE_CATEGORIES['special_tags']),
    }
    
    output = {
        'metadata': {
            'created_at': datetime.now().isoformat(),
            'version': '2.0',
            'total_categories': sum(stats.values()),
            'statistics': stats
        },
        'categories': COMPREHENSIVE_CATEGORIES
    }
    
    # JSONファイルとして保存
    output_file = f'comprehensive_categories_{datetime.now().strftime("%Y%m%d_%H%M%S")}.json'
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    
    return output_file, stats

if __name__ == "__main__":
    file, stats = export_category_structure()
    
    print("="*60)
    print("📚 包括的カテゴリ定義システム")
    print("="*60)
    
    print("\n📊 カテゴリ統計:")
    print(f"  メインカテゴリ・サブカテゴリ: {stats['main_categories_count']}種類")
    print(f"  時代カテゴリ: {stats['era_categories_count']}種類")
    print(f"  地域カテゴリ: {stats['region_categories_count']}種類")
    print(f"  特別タグ: {stats['special_tags_count']}種類")
    print("  ────────────────────────")
    print(f"  合計: {sum(stats.values())}種類のカテゴリ")
    
    print(f"\n✅ カテゴリ定義ファイル作成: {file}")