apiVersion: v1
kind: ServiceAccount
metadata:
  name: episode-factory
  labels:
    app: episode-factory

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: episode-factory-role
  labels:
    app: episode-factory
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: episode-factory-rolebinding
  labels:
    app: episode-factory
subjects:
- kind: ServiceAccount
  name: episode-factory
  namespace: episode-factory
roleRef:
  kind: Role
  name: episode-factory-role
  apiGroup: rbac.authorization.k8s.io